# Generated by Django 3.1 on 2020-08-20 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CustomerName', models.CharField(max_length=50, verbose_name='نام')),
                ('CustomerFamily', models.CharField(max_length=50, verbose_name='نام خانوادگی')),
                ('CustomerAge', models.IntegerField(verbose_name='سن')),
                ('Address', models.TextField(verbose_name='آدرس')),
            ],
            options={
                'verbose_name': 'مشتری ',
                'verbose_name_plural': 'مشتری',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductName', models.CharField(max_length=50, verbose_name='نام کالا')),
                ('ProductPrice', models.IntegerField(verbose_name='قیمت')),
                ('ProductStatus', models.IntegerField(choices=[(1, 'موجود در انبار'), (0, 'موجودی تا چند روز آینده')], verbose_name='وضعیت')),
            ],
            options={
                'verbose_name': 'کالا',
                'verbose_name_plural': 'کالا',
            },
        ),
        migrations.CreateModel(
            name='OrderApp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OrderDate', models.DateTimeField(verbose_name='تاریخ ثبت سفارش')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Store.customer', verbose_name='مشتری')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Store.product', verbose_name='کالا')),
            ],
            options={
                'verbose_name': 'سفارشات ',
                'verbose_name_plural': 'سفارشات',
            },
        ),
    ]
