# Generated by Django 3.1 on 2020-08-23 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ProductImage',
            field=models.ImageField(null=True, upload_to='product_images/', verbose_name='تصویر'),
        ),
    ]
