# Generated by Django 3.1 on 2020-08-23 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0002_product_productimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ProductImage',
            field=models.ImageField(default='null', upload_to='product_images/', verbose_name='تصویر'),
            preserve_default=False,
        ),
    ]
