# Generated by Django 3.1 on 2020-08-23 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0003_auto_20200823_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ProductDescription',
            field=models.TextField(default='null', verbose_name='توضیح مخنصری در مورد کالا'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='ProductStock',
            field=models.IntegerField(default=0, verbose_name='موجودی کالا'),
            preserve_default=False,
        ),
    ]
